# Generated by Django 5.0.3 on 2024-05-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pdf_id_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='requisitos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
